In [1]:
import pandas as pd
import requests

In [2]:
# Get Climate Change Knowledge Portal API dataset about rainfall in North America

# Save url
url = 'https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_pr_timeseries_annual_1901-2024_mean_historical_cru_ts4.09_mean/region_nac?_format=json'

In [3]:
# Call the API
response = requests.get(url)
response.raise_for_status()

In [4]:
# Convert to Python dict
data = response.json()

In [5]:
# Extract the nested 'data' dict
nested_data = data['data']

In [6]:
# Build a list with data
records = []
for region_code, timeseries in nested_data.items():
    if timeseries is None:
        continue  # skip regions with no data
    for date, value in timeseries.items():
        records.append({
            "region_code": region_code,
            "date": date,
            "rainfall_mm": value
        })

In [7]:
# Now try to create a DataFrame
rainfall_df = pd.DataFrame(records)

In [8]:
# Check on the df
rainfall_df.head()

  region_code     date  rainfall_mm
0         ABW  1901-07        420.9
1         ABW  1902-07        420.9
2         ABW  1903-07        420.9
3         ABW  1904-07        420.9
4         ABW  1905-07        420.9

In [9]:
# Check rainfall_df shape
rainfall_df.shape

(622976, 3)

In [ ]:
# Let's look at a list of region codes
list(rainfall_df['region_code'].unique())

['ABW',
 'ABW.14465',
 'AFG',
 'AFG.11',
 'AFG.110',
 'AFG.111',
 'AFG.112',
 'AFG.113',
 'AFG.114',
 'AFG.115',
 'AFG.116',
 'AFG.117',
 'AFG.118',
 'AFG.119',
 'AFG.12',
 'AFG.120',
 'AFG.121',
 'AFG.122',
 'AFG.123',
 'AFG.124',
 'AFG.125',
 'AFG.126',
 'AFG.127',
 'AFG.128',
 'AFG.129',
 'AFG.13',
 'AFG.130',
 'AFG.131',
 'AFG.132',
 'AFG.133',
 'AFG.134',
 'AFG.14',
 'AFG.15',
 'AFG.16',
 'AFG.17',
 'AFG.18',
 'AFG.19',
 'AGO',
 'AGO.8398',
 'AGO.8399',
 'AGO.8400',
 'AGO.8401',
 'AGO.8402',
 'AGO.8403',
 'AGO.8404',
 'AGO.8405',
 'AGO.8406',
 'AGO.8407',
 'AGO.8408',
 'AGO.8409',
 'AGO.8410',
 'AGO.8411',
 'AGO.8412',
 'AGO.8413',
 'AGO.8414',
 'AGO.8415',
 'AIA',
 'AIA.9416',
 'AIA.9417',
 'AIA.9418',
 'AIA.9419',
 'AIA.9420',
 'AIA.9421',
 'AIA.9422',
 'AIA.9425',
 'ALA',
 'ALA.841242',
 'ALB',
 'ALB.3305',
 'ALB.3306',
 'ALB.3307',
 'ALB.3308',
 'ALB.3309',
 'ALB.3310',
 'ALB.3311',
 'ALB.3312',
 'ALB.3313',
 'ALB.3314',
 'ALB.3315',
 'ALB.3316',
 'ALB.3317',
 'ALB.3318',
 'ALB.3319',
 'ALB.3320',
 'ALB.3321',
 'ALB.3322',
 'ALB.3323',
 'ALB.3324',
 'ALB.3325',
 'ALB.3326',
 'ALB.3327',
 'ALB.3328',
 'ALB.3329',
 'ALB.3330',
 'ALB.3331',
 'ALB.3332',
 'ALB.3333',
 'ALB.3334',
 'ALB.3335',
 'ALB.3336',
 'ALB.3337',
 'ALB.3338',
 'ALB.3339',
 'ALB.3340',
 'AND',
 'AND.7391',
 'AND.7392',
 'AND.7393',
 'AND.7394',
 'AND.7395',
 'AND.7396',
 'AND.7397',
 'ARE',
 'ARE.255149626',
 'ARE.255149627',
 'ARE.2553173',
 'ARE.2553177',
 'ARE.2553179',
 'ARE.2553180',
 'ARE.2553181',
 'ARG',
 'ARG.12429',
 'ARG.12430',
 'ARG.12431',
 'ARG.12432',
 'ARG.12433',
 'ARG.12434',
 'ARG.12435',
 'ARG.12436',
 'ARG.12437',
 'ARG.12438',
 'ARG.12439',
 'ARG.12440',
 'ARG.12441',
 'ARG.12442',
 'ARG.12443',
 'ARG.12444',
 'ARG.12445',
 'ARG.12446',
 'ARG.12447',
 'ARG.12448',
 'ARG.12449',
 'ARG.12450',
 'ARG.12451',
 'ARG.12452',
 'ARM',
 'ARM.13453',
 'ARM.13454',
 'ARM.13455',
 'ARM.13456',
 'ARM.13457',
 'ARM.13458',
 'ARM.13460',
 'ARM.13461',
 'ARM.13462',
 'ARM.13463',
 'ARM.13464',
 'ASM',
 'ASM.5389',
 'ATF',
 'ATF.881238',
 'ATF.881274',
 'ATF.881335',
 'ATF.881713',
 'ATF.882992',
 'ATG',
 'ATG.1140206',
 'ATG.1140207',
 'ATG.1140208',
 'ATG.1140209',
 'ATG.1140210',
 'ATG.1140211',
 'ATG.1140212',
 'ATG.1140213',
 'AUS',
 'AUS.17468',
 'AUS.17469',
 'AUS.17470',
 'AUS.17471',
 'AUS.17472',
 'AUS.17473',
 'AUS.17474',
 'AUS.17475',
 'AUS.17476',
 'AUS.17477',
 'AUT',
 'AUT.18478',
 'AUT.18479',
 'AUT.18480',
 'AUT.18481',
 'AUT.18482',
 'AUT.18483',
 'AUT.18484',
 'AUT.18485',
 'AUT.18486',
 'AZE',
 'AZE.19147297',
 'AZE.19147298',
 'AZE.19147299',
 'AZE.19147300',
 'AZE.19147301',
 'AZE.19147302',
 'AZE.19147303',
 'AZE.19147304',
 'AZE.19147305',
 'AZE.19147306',
 'BDI',
 'BDI.4340542',
 'BDI.4340543',
 'BDI.4340544',
 'BDI.4340545',
 'BDI.4340546',
 'BDI.4340547',
 'BDI.4340548',
 'BDI.4340549',
 'BDI.4340550',
 'BDI.4340551',
 'BDI.4340552',
 'BDI.4340553',
 'BDI.4340554',
 'BDI.4340555',
 'BDI.4340556',
 'BDI.4340557',
 'BDI.4340558',
 'BEL',
 'BEL.27600',
 'BEL.27601',
 'BEL.27602',
 'BEN',
 'BEN.29609',
 'BEN.29610',
 'BEN.29611',
 'BEN.29612',
 'BEN.29613',
 'BEN.29614',
 'BEN.29615',
 'BEN.29616',
 'BEN.29617',
 'BEN.29618',
 'BEN.29619',
 'BEN.29620',
 'BES',
 'BES.7500475104',
 'BFA',
 'BFA.4240276',
 'BFA.4240277',
 'BFA.4240278',
 'BFA.4240279',
 'BFA.4240280',
 'BFA.4240281',
 'BFA.4240282',
 'BFA.4240283',
 'BFA.4240284',
 'BFA.4240285',
 'BFA.4240286',
 'BFA.4240287',
 'BFA.4240288',
 'BGD',
 'BGD.231',
 'BGD.232',
 'BGD.233',
 'BGD.234',
 'BGD.235',
 'BGD.236',
 'BGD.237',
 'BGD.238',
 'BGR',
 'BGR.41702',
 'BGR.41703',
 'BGR.41704',
 'BGR.41705',
 'BGR.41706',
 'BGR.41707',
 'BGR.41708',
 'BGR.41709',
 'BGR.41710',
 'BGR.41711',
 'BGR.41712',
 'BGR.41713',
 'BGR.41714',
 'BGR.41715',
 'BGR.41716',
 'BGR.41717',
 'BGR.41718',
 'BGR.41719',
 'BGR.41720',
 'BGR.41721',
 'BGR.41722',
 'BGR.41723',
 'BGR.41724',
 'BGR.41725',
 'BGR.41726',
 'BGR.41727',
 'BGR.41728',
 'BGR.41729',
 'BHR',
 'BHR.21562',
 'BHR.21563',
 'BHR.21564',
 'BHR.21565',
 'BHR.21566',
 'BHR.21567',
 'BHR.21568',
 'BHR.21569',
 'BHR.21570',
 'BHR.21571',
 'BHR.21572',
 'BHR.21573',
 'BHS',
 'BHS.20561',
 'BIH',
 'BIH.34652',
 'BIH.34653',
 'BLR',
 'BLR.26593',
 'BLR.26594',
 'BLR.26595',
 'BLR.26596',
 'BLR.26597',
 'BLR.26598',
 'BLR.26599',
 'BLZ',
 'BLZ.28603',
 'BLZ.28604',
 'BLZ.28605',
 'BLZ.28606',
 'BLZ.28607',
 'BLZ.28608',
 'BMU',
 'BMU.30621',
 'BOL',
 'BOL.3340443',
 'BOL.3340444',
 'BOL.3340445',
 'BOL.3340446',
 'BOL.3340447',
 'BOL.3340448',
 'BOL.3340449',
 'BOL.3340450',
 'BOL.33648',
 'BRA',
 'BRA.37665',
 'BRA.37666',
 'BRA.37667',
 'BRA.37668',
 'BRA.37669',
 'BRA.37670',
 'BRA.37671',
 'BRA.37672',
 'BRA.37673',
 'BRA.37674',
 'BRA.37675',
 'BRA.37676',
 'BRA.37677',
 'BRA.37678',
 'BRA.37679',
 'BRA.37680',
 'BRA.37681',
 'BRA.37682',
 'BRA.37683',
 'BRA.37684',
 'BRA.37685',
 'BRA.37686',
 'BRA.37687',
 'BRA.37688',
 'BRA.37689',
 'BRA.37690',
 'BRA.37691',
 'BRA.37694',
 'BRB',
 'BRB.24581',
 'BRB.24582',
 'BRB.24583',
 'BRB.24584',
 'BRB.24585',
 'BRB.24586',
 'BRB.24587',
 'BRB.24588',
 'BRB.24589',
 'BRB.24590',
 'BRB.24591',
 'BRN',
 'BRN.40698',
 'BRN.40699',
 'BRN.40700',
 'BRN.40701',
 'BTN',
 'BTN.3141308',
 'BTN.3141309',
 'BTN.3141310',
 'BTN.3141311',
 'BTN.3141312',
 'BTN.3141313',
 'BTN.3141314',
 'BTN.31622',
 'BTN.31623',
 'BTN.31625',
 'BTN.31627',
 'BTN.31628',
 'BTN.31629',
 'BTN.31631',
 'BTN.31635',
 'BTN.31636',
 'BTN.31637',
 'BTN.31638',
 'BTN.31639',
 'BTN.31640',
 'BWA',
 'BWA.35654',
 'BWA.35655',
 'BWA.35656',
 'BWA.35657',
 'BWA.35658',
 'BWA.35659',
 'BWA.35660',
 'BWA.35661',
 'BWA.35662',
 'BWA.35663',
 'CAF',
 'CAF.4967154',
 'CAF.49853',
 'CAF.49854',
 'CAF.49855',
 'CAF.49856',
 'CAF.49857',
 'CAF.49858',
 'CAF.49859',
 'CAF.49860',
 'CAF.49861',
 'CAF.49862',
 'CAF.49863',
 'CAF.49864',
 'CAF.49865',
 'CAF.49866',
 'CAF.49867',
 'CAF.49868',
 'CAN',
 'CAN.461',
 'CAN.4610',
 'CAN.4611',
 'CAN.4612',
 'CAN.4613',
 'CAN.462',
 'CAN.463',
 'CAN.464',
 'CAN.465',
 'CAN.466',
 'CAN.467',
 'CAN.468',
 'CAN.469',
 'CCK',
 'CCK.56933',
 'CHE',
 'CHE.2372807',
 'CHE.2372808',
 'CHE.2372809',
 'CHE.2372810',
 'CHE.2372811',
 'CHE.2372812',
 'CHE.2372813',
 'CHE.2372814',
 'CHE.2372815',
 'CHE.2372816',
 'CHE.2372817',
 'CHE.2372818',
 'CHE.2372819',
 'CHE.2372820',
 'CHE.2372821',
 'CHE.2372822',
 'CHE.2372823',
 'CHE.2372824',
 'CHE.2372825',
 'CHE.2372826',
 'CHE.2372827',
 'CHE.2372828',
 'CHE.2372829',
 'CHE.2372830',
 'CHE.2372831',
 'CHE.2372832',
 'CHL',
 'CHL.51149630',
 'CHL.51883',
 'CHL.51884',
 'CHL.51885',
 'CHL.51886',
 'CHL.51887',
 'CHL.51888',
 'CHL.51889',
 'CHL.51891',
 'CHL.51892',
 'CHL.51893',
 'CHL.5191501',
 'CHL.5191502',
 'CHL.5191503',
 'CHL.5191504',
 'CHN',
 'CHN.147295898',
 'CHN.147295899',
 'CHN.147295900',
 'CHN.147295901',
 'CHN.147295902',
 'CHN.147295903',
 'CHN.147295904',
 'CHN.147295905',
 'CHN.147295906',
 'CHN.147295907',
 'CHN.147295908',
 'CHN.147295909',
 'CHN.147295911',
 'CHN.147295912',
 'CHN.147295913',
 'CHN.147295914',
 'CHN.147295915',
 'CHN.147295916',
 'CHN.147295917',
 'CHN.147295918',
 'CHN.147295919',
 'CHN.147295920',
 'CHN.147295921',
 'CHN.147295922',
 'CHN.147295923',
 'CHN.147295924',
 'CHN.147295926',
 'CHN.147295927',
 'CHN.147295928',
 'CHN.147295929',
 'CHN.147295930',
 'CIV',
 'CIV.661',
 'CIV.6610',
 'CIV.6611',
 'CIV.6612',
 'CIV.6613',
 'CIV.6614',
 'CIV.662',
 'CIV.663',
 'CIV.664',
 'CIV.665',
 'CIV.666',
 'CIV.667',
 'CIV.668',
 'CIV.669',
 'CMR',
 'CMR.45815',
 'CMR.45816',
 'CMR.45817',
 'CMR.45818',
 'CMR.45819',
 'CMR.45820',
 'CMR.45821',
 'CMR.45822',
 'CMR.45823',
 'CMR.45824',
 'COD',
 'COD.681066',
 'COD.681067',
 'COD.681068',
 'COD.681069',
 'COD.681070',
 'COD.681071',
 'COD.681072',
 'COD.681073',
 'COD.681074',
 'COD.681075',
 'COD.681076',
 'COD.681077',
 'COD.681078',
 'COD.681079',
 'COD.681080',
 'COD.681081',
 'COD.681082',
 'COD.681083',
 'COD.681084',
 'COD.681085',
 'COD.681086',
 'COD.681087',
 'COD.681088',
 'COD.681089',
 'COD.681090',
 'COD.681091',
 'COG',
 'COG.59190431',
 'COG.59190432',
 'COG.59190433',
 'COG.59190434',
 'COG.59970',
 'COG.59971',
 'COG.59972',
 'COG.59974',
 'COG.59975',
 'COG.59976',
 'COG.59977',
 'COG.59979',
 'COK',
 'COK.60980',
 'COL',
 'COL.57934',
 'COL.57935',
 'COL.57936',
 'COL.57937',
 'COL.57938',
 'COL.57939',
 'COL.57941',
 'COL.57942',
 'COL.57943',
 'COL.57944',
 'COL.57945',
 'COL.57946',
 'COL.57947',
 'COL.57948',
 'COL.579481',
 'COL.57949',
 'COL.57950',
 'COL.57951',
 'COL.57952',
 'COL.57953',
 'COL.57954',
 'COL.57955',
 'COL.57956',
 'COL.57957',
 'COL.57958',
 'COL.57959',
 'COL.57960',
 'COL.57961',
 'COL.57962',
 'COL.57963',
 'COL.57964',
 'COL.57965',
 'COL.57966',
 'COM',
 'COM.58967',
 'COM.58968',
 'COM.58969',
 'CPV',
 'CPV.47838',
 'CPV.47839',
 'CPV.47840',
 'CPV.47841',
 'CPV.47842',
 'CPV.47843',
 'CPV.47844',
 'CPV.47845',
 'CPV.47846',
 'CPV.47847',
 'CPV.47848',
 'CPV.47849',
 'CPV.47850',
 'CPV.47851',
 'CRI',
 'CRI.61981',
 'CRI.61982',
 'CRI.61983',
 'CRI.61984',
 'CRI.61985',
 'CRI.61986',
 'CRI.61987',
 'CUB',
 'CUB.631009',
 'CUB.631010',
 'CUB.631011',
 'CUB.631012',
 'CUB.631013',
 'CUB.631014',
 'CUB.631015',
 'CUB.631016',
 'CUB.631017',
 'CUB.631018',
 'CUB.631019',
 'CUB.631020',
 'CUB.631021',
 'CUB.631022',
 'CUB.631023',
 'CUW',
 'CUW.7500275102',
 'CXR',
 'CXR.54931',
 'CYM',
 'CYM.4868742',
 'CYP',
 'CYP.6475401',
 'CYP.6475403',
 'CYP.6475404',
 'CYP.6475405',
 'CYP.6475406',
 'CYP.6475407',
 'CZE',
 'CZE.651030',
 'CZE.651031',
 'CZE.651032',
 'CZE.651033',
 'CZE.651034',
 'CZE.651035',
 'CZE.651036',
 'CZE.651037',
 'DEU',
 'DEU.931308',
 'DEU.931309',
 'DEU.931310',
 'DEU.931311',
 'DEU.931312',
 'DEU.931313',
 'DEU.931314',
 'DEU.931315',
 'DEU.931316',
 'DEU.931317',
 'DEU.931318',
 'DEU.931319',
 'DEU.931320',
 'DEU.931321',
 'DEU.931322',
 'DEU.931323',
 'DIS.990011',
 'DIS.990022',
 'DIS.990044',
 'DIS.990055',
 'DIS.990066',
 'DIS.990099',
 'DIS.9901212',
 'DIS.9901313',
 'DIS.9901414',
 'DIS.9901515',
 'DIS.9901616',
 'DIS.9901717',
 'DIS.9901818',
 'DIS.9901919',
 'DIS.9902020',
 'DIS.9902121',
 'DIS.9902222',
 'DIS.9902323',
 'DIS.9902424',
 'DIS.9902626',
 'DIS.9902727',
 'DIS.9902828',
 'DIS.9902929',
 'DIS.9903030',
 'DIS.9903131',
 'DISPUTED',
 'DIV002418',
 'DIV003449',
 'DIV083903',
 'DIV086580',
 'DJI',
 'DJI.701',
 'DJI.702',
 'DJI.703',
 'DJI.704',
 'DJI.705',
 'DMA',
 'DMA.711098',
 'DMA.711099',
 'DMA.711100',
 'DMA.711101',
 'DMA.711102',
 'DMA.711103',
 'DMA.711104',
 'DMA.711105',
 'DMA.711106',
 'DMA.711107',
 'DNK',
 'DNK.691',
 'DNK.692',
 'DNK.693',
 'DNK.694',
 'DNK.695',
 'DOM',
 'DOM.721108',
 'DOM.721109',
 'DOM.721110',
 'DOM.721111',
 'DOM.721112',
 'DOM.721113',
 'DOM.721114',
 'DOM.721115',
 'DOM.721116',
 'DOM.721117',
 'DOM.721118',
 'DOM.721119',
 'DOM.721120',
 'DOM.721121',
 'DOM.721122',
 'DOM.721123',
 'DOM.721124',
 'DOM.721125',
 'DOM.721126',
 'DOM.721127',
 'DOM.721128',
 'DOM.721129',
 'DOM.721130',
 'DOM.721131',
 'DOM.721132',
 'DOM.721133',
 'DOM.721134',
 'DOM.7236854',
 'DOM.7236855',
 'DOM.7236856',
 'DOM.7236857',
 'DOM.7236858',
 'DZA',
 'DZA.4341',
 'DZA.4342',
 'DZA.4343',
 'DZA.4344',
 'DZA.4345',
 'DZA.4346',
 'DZA.4347',
 'DZA.4348',
 'DZA.4349',
 'DZA.4350',
 'DZA.4351',
 'DZA.4352',
 'DZA.4353',
 'DZA.4354',
 'DZA.4355',
 'DZA.4356',
 'DZA.4357',
 'DZA.4358',
 'DZA.4359',
 'DZA.4360',
 'DZA.4361',
 'DZA.4362',
 'DZA.4363',
 'DZA.4364',
 'DZA.4365',
 'DZA.4366',
 'DZA.4367',
 'DZA.4368',
 'DZA.4369',
 'DZA.4370',
 'DZA.4371',
 'DZA.4372',
 'DZA.4373',
 'DZA.4374',
 'DZA.4375',
 'DZA.4376',
 'DZA.4377',
 'DZA.4378',
 'DZA.4379',
 'DZA.4380',
 'DZA.4381',
 'DZA.4382',
 'DZA.4383',
 'DZA.4384',
 'DZA.4385',
 'DZA.4386',
 'DZA.4387',
 'DZA.4388',
 'EAP000001',
 'EAP000302',
 'EAP000369',
 'EAP000370',
 'EAP000422',
 'EAP000423',
 'EAP000480',
 'EAP000481',
 'EAP000505',
 'EAP000514',
 'EAP000515',
 'EAP000572',
 'EAP000583',
 'EAP000652',
 'EAP000653',
 'EAP000657',
 'EAP000658',
 'EAP000669',
 'EAP000690',
 'EAP000694',
 'EAP000708',
 'EAP000709',
 'EAP000738',
 'EAP000740',
 'EAP000741',
 'EAP000742',
 'EAP000766',
 'EAP000767',
 'EAP000769',
 'EAP000785',
 'EAP000786',
 'EAP000988',
 'EAP000989',
 'EAP001169',
 'EAP001180',
 'EAP001228',
 'EAP001229',
 'EAP001277',
 'EAP001278',
 'EAP001299',
 'EAP001300',
 'EAP001402',
 'EAP001500',
 'EAP001501',
 'EAP001509',
 'EAP001566',
 'EAP001582',
 'EAP001583',
 'EAP001702',
 'EAP001703',
 'EAP001704',
 'EAP001782',
 'EAP001783',
 'EAP001835',
 'EAP002118',
 'EAP002119',
 'EAP002220',
 'EAP002250',
 'EAP002279',
 'EAP002305',
 'EAP002306',
 'EAP002307',
 'EAP002321',
 'EAP002322',
 'EAP002323',
 'EAP002381',
 'EAP002382',
 'EAP002419',
 'EAP002431',
 'EAP003124',
 'EAP003727',
 'EAP003894',
 'EAP004004',
 'EAP004036',
 'EAP004123',
 'EAP004124',
 'EAP004187',
 'EAP004188',
 'EAP004578',
 'EAP004637',
 'EAP004691',
 'EAP004692',
 'EAP004750',
 'EAP004772',
 'EAP004773',
 'EAP005021',
 'EAP005026',
 'EAP005027',
 'EAP005028',
 'EAP005029',
 'EAP005031',
 'EAP005032',
 'EAP005034',
 'EAP005037',
 'EAP005038',
 'EAP005039',
 'EAP005041',
 'EAP005043',
 'EAP005044',
 'EAP005045',
 'EAP005047',
 'EAP005048',
 'EAP005052',
 'EAP005055',
 'EAP005058',
 'EAP005059',
 'EAP005061',
 'EAP005070',
 'EAP005074',
 'EAP005078',
 'EAP005079',
 'EAP005081',
 'EAP005083',
 'EAP005085',
 'EAP005090',
 'EAP005091',
 'EAP005094',
 'EAP005095',
 'EAP005098',
 'EAP005110',
 'EAP005121',
 'EAP005127',
 'EAP005153',
 'EAP005314',
 'EAP005488',
 'EAP005542',
 'EAP005587',
 'EAP005595',
 'EAP008155',
 'EAP009532',
 'EAP013625',
 'EAP018680',
 'EAP041619',
 'EAP041643',
 'EAP043803',
 'EAP043813',
 'EAP044966',
 'EAP044999',
 'EAP046269',
 'EAP046293',
 'EAP054826',
 'EAP054837',
 'EAP057864',
 'EAP057883',
 'EAP060357',
 'EAP060374',
 'EAP062725',
 'EAP062762',
 'EAP067975',
 'EAP067976',
 'EAP069419',
 'EAP069435',
 'EAP074830',
 'EAP074831',
 ...]

In [10]:
# Let's look at unique region codes
rainfall_df['region_code'].nunique()

5024

In [14]:
# We need to find only regions in Canada and the USA
north_america_codes = ['CAN', 'USA']  # add more if needed
rainfall_df_na = rainfall_df[rainfall_df['region_code'].str.startswith(tuple(north_america_codes))]

In [15]:
# Look at new rainfall_df_na
rainfall_df_na.head()

      region_code     date  rainfall_mm
54064         CAN  1901-07       538.38
54065         CAN  1902-07       549.26
54066         CAN  1903-07       540.08
54067         CAN  1904-07       531.71
54068         CAN  1905-07       531.56

In [16]:
# Look at unique region codes
rainfall_df_na['region_code'].nunique()

66

In [17]:
# Look at region codes
rainfall_df_na['region_code'].unique()

array(['CAN', 'CAN.461', 'CAN.4610', 'CAN.4611', 'CAN.4612', 'CAN.4613',
       'CAN.462', 'CAN.463', 'CAN.464', 'CAN.465', 'CAN.466', 'CAN.467',
       'CAN.468', 'CAN.469', 'USA', 'USA.2593214', 'USA.2593215',
       'USA.2593216', 'USA.2593217', 'USA.2593218', 'USA.2593219',
       'USA.2593220', 'USA.2593221', 'USA.2593222', 'USA.2593223',
       'USA.2593224', 'USA.2593225', 'USA.2593226', 'USA.2593227',
       'USA.2593228', 'USA.2593229', 'USA.2593230', 'USA.2593231',
       'USA.2593232', 'USA.2593233', 'USA.2593234', 'USA.2593235',
       'USA.2593236', 'USA.2593237', 'USA.2593238', 'USA.2593239',
       'USA.2593240', 'USA.2593241', 'USA.2593242', 'USA.2593243',
       'USA.2593244', 'USA.2593245', 'USA.2593246', 'USA.2593247',
       'USA.2593248', 'USA.2593249', 'USA.2593250', 'USA.2593251',
       'USA.2593252', 'USA.2593253', 'USA.2593254', 'USA.2593255',
       'USA.2593256', 'USA.2593257', 'USA.2593258', 'USA.2593259',
       'USA.2593260', 'USA.2593261', 'USA.2593262', 'USA.2593263',
       'USA.2593264'], dtype=object)

In [18]:
# Check for na
rainfall_df_na.isna().sum()

region_code    0
date           0
rainfall_mm    0
dtype: int64