In [1]:
!pip install boto3

Requirement already satisfied: boto3 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (1.40.21)
Requirement already satisfied: botocore<1.41.0,>=1.40.21 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from boto3) (1.40.21)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.14.0,>=0.13.0 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from boto3) (0.13.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from botocore<1.41.0,>=1.40.21->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from botocore<1.41.0,>=1.40.21->boto3) (2.2.2)
Requirement already satisfied: six>=1.5 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.41.0,>=1.40.21->boto3) (1.16.0)

In [2]:
!pip install netCDF4
!pip install h5netcdf

Requirement already satisfied: netCDF4 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (1.7.2)
Requirement already satisfied: cftime in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from netCDF4) (1.6.4.post1)
Requirement already satisfied: certifi in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from netCDF4) (2024.8.30)
Requirement already satisfied: numpy in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from netCDF4) (1.26.4)
Requirement already satisfied: h5netcdf in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (1.6.4)
Requirement already satisfied: h5py in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from h5netcdf) (3.11.0)
Requirement already satisfied: packaging in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from h5netcdf) (23.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\nbart\anaconda3\envs\dev\lib\site-packages (from h5py->h5netcdf) (1.26.4)

In [3]:
# import dependencies
import pandas as pd
import os
import requests
import json
import xarray as xr
import boto3

In [4]:
# Load Our World in Data CO2 data ('owid-co2-data.csv')
owid_co2_df = pd.read_csv('Resources/owid-co2-data.csv')
owid_co2_df.head(20)

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,1755,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Afghanistan,1756,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,1757,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,1758,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Afghanistan,1759,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Afghanistan,1760,AFG,2866255.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Afghanistan,1761,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Afghanistan,1762,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Afghanistan,1763,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Afghanistan,1764,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Afghanistan,1765,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Afghanistan,1766,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Afghanistan,1767,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Afghanistan,1768,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Afghanistan,1769,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

source: https://github.com/owid/co2-data?tab=readme-ov-file

In [5]:
# Look at columns of owid_co2_df
owid_co2_df.columns

Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share'],
      dtype='object')

In [6]:
# Load Cost and Affordability of a Healthy Diet (CoAHD) dataset ('FAO_CAHD.csv')
healthy_diet_cost_df = pd.read_csv('Resources/FAO_CAHD.csv')

# See all the columns
pd.set_option("display.max_columns", None)

# See truncated entries
pd.set_option("display.max_colwidth", None)

healthy_diet_cost_df.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,SEX_LABEL,AGE,AGE_LABEL,URBANISATION,URBANISATION_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3,COMP_BREAKDOWN_3_LABEL,TIME_PERIOD,OBS_VALUE,DATABASE_ID,DATABASE_ID_LABEL,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,FAO_CAHD_7005,Percentage of the population unable to afford a healthy diet (percent),_T,Total,_T,All age ranges or no breakdown by age,_T,Total,PT,Percentage,_Z,Not Applicable,_Z,Not Applicable,_Z,Not Applicable,2017,24.3,FAO_CAHD,Cost and Affordability of a Healthy Diet (CoAHD),0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,FAO_CAHD_7005,Percentage of the population unable to afford a healthy diet (percent),_T,Total,_T,All age ranges or no breakdown by age,_T,Total,PT,Percentage,_Z,Not Applicable,_Z,Not Applicable,_Z,Not Applicable,2018,17.6,FAO_CAHD,Cost and Affordability of a Healthy Diet (CoAHD),0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,FAO_CAHD_7005,Percentage of the population unable to afford a healthy diet (percent),_T,Total,_T,All age ranges or no breakdown by age,_T,Total,PT,Percentage,_Z,Not Applicable,_Z,Not Applicable,_Z,Not Applicable,2019,14.6,FAO_CAHD,Cost and Affordability of a Healthy Diet (CoAHD),0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,FAO_CAHD_7005,Percentage of the population unable to afford a healthy diet (percent),_T,Total,_T,All age ranges or no breakdown by age,_T,Total,PT,Percentage,_Z,Not Applicable,_Z,Not Applicable,_Z,Not Applicable,2020,13.9,FAO_CAHD,Cost and Affordability of a Healthy Diet (CoAHD),0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,FAO_CAHD_7005,Percentage of the population unable to afford a healthy diet (percent),_T,Total,_T,All age ranges or no breakdown by age,_T,Total,PT,Percentage,_Z,Not Applicable,_Z,Not Applicable,_Z,Not Applicable,2021,12.6,FAO_CAHD,Cost and Affordability of a Healthy Diet (CoAHD),0,Units,RATIO,Ratio,602,CCYY,A,Normal value,PU,Public

source: https://data360.worldbank.org/en/dataset/FAO_CAHD

In [7]:
# Let's get a list of all these column headers
healthy_diet_cost_df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'FREQ_LABEL', 'REF_AREA',
       'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL', 'SEX', 'SEX_LABEL',
       'AGE', 'AGE_LABEL', 'URBANISATION', 'URBANISATION_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL', 'TIME_PERIOD',
       'OBS_VALUE', 'DATABASE_ID', 'DATABASE_ID_LABEL', 'UNIT_MULT',
       'UNIT_MULT_LABEL', 'UNIT_TYPE', 'UNIT_TYPE_LABEL', 'TIME_FORMAT',
       'TIME_FORMAT_LABEL', 'OBS_STATUS', 'OBS_STATUS_LABEL', 'OBS_CONF',
       'OBS_CONF_LABEL'],
      dtype='object')

In [8]:
# List of preferred columns
columns_list = [
    'REF_AREA_LABEL', 'INDICATOR_LABEL', 'AGE_LABEL', 'URBANISATION_LABEL', 'UNIT_MEASURE_LABEL', 'UNIT_MULT', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_STATUS_LABEL'
]

In [9]:
# New condensed df
edited_diet_df = healthy_diet_cost_df[columns_list]
edited_diet_df.head()

,REF_AREA_LABEL,INDICATOR_LABEL,AGE_LABEL,URBANISATION_LABEL,UNIT_MEASURE_LABEL,UNIT_MULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS_LABEL
0,Albania,Percentage of the population unable to afford a healthy diet (percent),All age ranges or no breakdown by age,Total,Percentage,0,2017,24.3,Normal value
1,Albania,Percentage of the population unable to afford a healthy diet (percent),All age ranges or no breakdown by age,Total,Percentage,0,2018,17.6,Normal value
2,Albania,Percentage of the population unable to afford a healthy diet (percent),All age ranges or no breakdown by age,Total,Percentage,0,2019,14.6,Normal value
3,Albania,Percentage of the population unable to afford a healthy diet (percent),All age ranges or no breakdown by age,Total,Percentage,0,2020,13.9,Normal value
4,Albania,Percentage of the population unable to afford a healthy diet (percent),All age ranges or no breakdown by age,Total,Percentage,0,2021,12.6,Normal value

In [10]:
# Look at unique values in INDICATOR_LABEL column
edited_diet_df['INDICATOR_LABEL'].unique()

array(['Percentage of the population unable to afford a healthy diet (percent)',
       'Number of people unable to afford a healthy diet (million)'],
      dtype=object)

In [11]:
# Look at unique values in AGE_LABEL column
edited_diet_df['AGE_LABEL'].unique()

array(['All age ranges or no breakdown by age'], dtype=object)

In [12]:
# Look at unique values in URBANISATION_LABEL column
edited_diet_df['URBANISATION_LABEL'].unique()

array(['Total'], dtype=object)

In [13]:
# Look at unique values in UNIT_MEASURE_LABEL column
edited_diet_df['UNIT_MEASURE_LABEL'].unique()

array(['Percentage', 'Persons'], dtype=object)

In [14]:
# Look at unique values in OBS_STATUS_LABEL column
edited_diet_df['OBS_STATUS_LABEL'].unique()

array(['Normal value'], dtype=object)

'AGE_LABEL', 'URBANISATION LABEL', 'OBS_STATUS_LABEL' columns only have one unique entry. 'AGE_LABEL' means all ages are included, this column can be dropped. 'URBANISATION_LABEL' is always "Total", this column can be dropped. 'OBS_STATUS_LABEL' is always "Normal", this column can be dropped.

In [15]:
# Drop unnecessary columns
edited_diet_df = edited_diet_df.drop(['AGE_LABEL', 'URBANISATION_LABEL', 'OBS_STATUS_LABEL'],
                                     axis=1
                                     )

In [16]:
edited_diet_df.head()

,REF_AREA_LABEL,INDICATOR_LABEL,UNIT_MEASURE_LABEL,UNIT_MULT,TIME_PERIOD,OBS_VALUE
0,Albania,Percentage of the population unable to afford a healthy diet (percent),Percentage,0,2017,24.3
1,Albania,Percentage of the population unable to afford a healthy diet (percent),Percentage,0,2018,17.6
2,Albania,Percentage of the population unable to afford a healthy diet (percent),Percentage,0,2019,14.6
3,Albania,Percentage of the population unable to afford a healthy diet (percent),Percentage,0,2020,13.9
4,Albania,Percentage of the population unable to afford a healthy diet (percent),Percentage,0,2021,12.6

In [17]:
# Look at value counts for INDICATOR_LABEL column
edited_diet_df['INDICATOR_LABEL'].value_counts()

INDICATOR_LABEL
Percentage of the population unable to afford a healthy diet (percent)    1202
Number of people unable to afford a healthy diet (million)                1122
Name: count, dtype: int64

In [18]:
# Look at value counts for UNIT_MEASURES_LABEL
edited_diet_df['UNIT_MEASURE_LABEL'].value_counts()

UNIT_MEASURE_LABEL
Percentage    1202
Persons       1122
Name: count, dtype: int64

In [19]:
# Drop INDICATOR_LABEL column, as it coincides directly with UNIT_MEASURE_LABEL and is more cumbersome
edited_diet_df = edited_diet_df.drop(['INDICATOR_LABEL'], axis=1)

In [20]:
edited_diet_df.head()

  REF_AREA_LABEL UNIT_MEASURE_LABEL  UNIT_MULT  TIME_PERIOD  OBS_VALUE
0        Albania         Percentage          0         2017       24.3
1        Albania         Percentage          0         2018       17.6
2        Albania         Percentage          0         2019       14.6
3        Albania         Percentage          0         2020       13.9
4        Albania         Percentage          0         2021       12.6

Because they use different units of measurement, it's hard to know what to do. Roughly half the dataset uses different units. It would be possible to manually calculate the percentage or number of persons (convert the data to one or the other units). Or maybe just drop the entries counted in 'Persons'. Let's look at an example of a row counted in 'Persons'.

In [21]:
# Look at value counts for UNIT_MULT column
edited_diet_df['UNIT_MULT'].value_counts()

UNIT_MULT
0    1202
6    1122
Name: count, dtype: int64

In [22]:
# Find a persons row
row = edited_diet_df[edited_diet_df['UNIT_MEASURE_LABEL'] == "Persons"]
row

     REF_AREA_LABEL UNIT_MEASURE_LABEL  UNIT_MULT  TIME_PERIOD  OBS_VALUE
1202        Albania            Persons          6         2017        0.7
1203        Albania            Persons          6         2018        0.5
1204        Albania            Persons          6         2019        0.4
1205        Albania            Persons          6         2020        0.4
1206        Albania            Persons          6         2021        0.4
...             ...                ...        ...          ...        ...
2319          Ghana            Persons          6         2023       22.4
2320         Greece            Persons          6         2024        1.7
2321        Armenia            Persons          6         2024        1.9
2322        Armenia            Persons          6         2023        1.5
2323         Greece            Persons          6         2023        1.8

[1122 rows x 5 columns]

In [23]:
# Look at REF_AREA_LABEL value counts
edited_diet_df['REF_AREA_LABEL'].value_counts()

REF_AREA_LABEL
Albania      16
Jordan       16
Myanmar      16
Namibia      16
Nepal        16
             ..
Malta         8
St. Lucia     8
Argentina     2
Zimbabwe      2
Qatar         1
Name: count, Length: 153, dtype: int64

In [24]:
# Look at TIME_PERIOD value counts
edited_diet_df['TIME_PERIOD'].value_counts()

TIME_PERIOD
2017    297
2018    292
2023    291
2019    290
2020    290
2021    289
2022    289
2024    286
Name: count, dtype: int64

Open Aquastat CSV file (FAO-AS.csv) from: https://data360.worldbank.org/en/dataset/FAO_AS

Was hoping for rainfall data, doesn't seem to be in here.

In [26]:
# Load ClimateWatch dataset from
climate_df = pd.read_csv('Resources/WRI_CLIMATEWATCH.csv')
climate_df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Resources/WRI_CLIMATEWATCH.csv'

In [ ]:
# Look at climate_head columns
climate_df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'FREQ_LABEL', 'REF_AREA',
       'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL', 'SEX', 'SEX_LABEL',
       'AGE', 'AGE_LABEL', 'URBANISATION', 'URBANISATION_LABEL',
       'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_2_LABEL',
       'COMP_BREAKDOWN_3', 'COMP_BREAKDOWN_3_LABEL', 'TIME_PERIOD',
       'OBS_VALUE', 'DATABASE_ID', 'DATABASE_ID_LABEL', 'UNIT_MULT',
       'UNIT_MULT_LABEL', 'UNIT_TYPE', 'UNIT_TYPE_LABEL', 'TIME_FORMAT',
       'TIME_FORMAT_LABEL', 'OBS_STATUS', 'OBS_STATUS_LABEL', 'OBS_CONF',
       'OBS_CONF_LABEL'],
      dtype='object')

In [ ]:
# Look at unique values of "INDICATOR_LABEL" column
climate_df['INDICATOR_LABEL'].value_counts()

INDICATOR_LABEL
Greenhouse gas (GHG) emissions caused by the transportation sector    12202
Name: count, dtype: int64

In [ ]:
# Load data dictionary for climate_df
climate_dict_df = pd.read_csv('Resources/WRI_CLIMATEWATCH_DATADICT.csv')
climate_dict_df

,VARIABLE_ID,VARIABLE_LABEL,VARIABLE_DESCRIPTION,VARIABLE_DATA_TYPE,VARIABLE_REQUIRED
0,FREQ,Frequency of observation,Time interval at which observations occur over a given time period.,String,True
1,FREQ_LABEL,Frequency of observation,Time interval at which observations occur over a given time period.,String,True
2,REF_AREA,Reference area,Country or geographic area to which the measured statistical phenomenon relates.,String,True
3,REF_AREA_LABEL,Reference area,Country or geographic area to which the measured statistical phenomenon relates.,String,True
4,INDICATOR,Statistical indicator,"Data element that represents statistical data for a specified time, place, and other characteristics, and is corrected for at least one dimension (usually size) to allow for meaningful comparisons.",String,True
5,INDICATOR_LABEL,Statistical indicator,"Data element that represents statistical data for a specified time, place, and other characteristics, and is corrected for at least one dimension (usually size) to allow for meaningful comparisons.",String,True
6,SEX,Sex,State of being male or female.,String,True
7,SEX_LABEL,Sex,State of being male or female.,String,True
8,AGE,Age,Length of time that an entity has lived or existed.,String,True
9,AGE_LABEL,Age,Length of time that an entity has lived or existed.,String,True
10,URBANISATION,Degree of urbanisation,"Refers to Total, Urban, or Rural location.",String,True
11,URBANISATION_LABEL,Degree of urbanisation,"Refers to Total, Urban, or Rural location.",String,True
12,UNIT_MEASURE,Unit of measure,Unit in which the data values are expressed.,String,True
13,UNIT_MEASURE_LABEL,Unit of measure,Unit in which the data values are expressed.,String,True
14,COMP_BREAKDOWN_1,Custom Dimension 1,NaN,String,True
15,COMP_BREAKDOWN_1_LABEL,Custom Dimension 1,NaN,String,True
16,COMP_BREAKDOWN_2,Custom Dimension 2,NaN,String,True
17,COMP_BREAKDOWN_2_LABEL,Custom Dimension 2,NaN,String,True
18,COMP_BREAKDOWN_3,Custom Dimension 3,NaN,String,True
19,COMP_BREAKDOWN_3_LABEL,Custom Dimension 3,NaN,String,True
20,TIME_PERIOD,Time period,Timespan or point in time to which the observation actually refers.,ObservationalTimePeriod,True
21,OBS_VALUE,Observation value,Value of a particular variable.,Float,False
22,AGG_METHOD,Aggregation method,NaN,String,False
23,AGG_METHOD_LABEL,Aggregation method,NaN,String,False
24,DECIMALS,Decimals,Number of digits of an observation to the right of a decimal point.,String,False
25,DECIMALS_LABEL,Decimals,Number of digits of an observation to the right of a decimal point.,String,False
26,DATABASE_ID,Identifier of database,NaN,String,True
27,DATABASE_ID_LABEL,Identifier of database,NaN,String,True
28,COMMENT_TS,"Title complement, detailed description of the series",NaN,NaN,False
29,UNIT_MULT,Unit multiplier,Exponent in base 10 specified so that multiplying the observation numeric values by 10^UNIT_MULT gives a value expressed in the unit of measure.,NaN,True
30,UNIT_MULT_LABEL,Unit multiplier,Exponent in base 10 specified so that multiplying the observation numeric values by 10^UNIT_MULT gives a value expressed in the unit of measure.,NaN,True
31,DATA_SOURCE,Data source,Location or service from where data or metadata can be obtained.,String,False
32,DATA_SOURCE_LABEL,Data source,Location or service from where data or metadata can be obtained.,String,False
33,UNIT_TYPE,Base type of unit,NaN,String,True
34,UNIT_TYPE_LABEL,Base type of unit,NaN,String,True
35,TIME_FORMAT,Time format,Technical format for the representation of time.,NaN,False
36,TIME_FORMAT_LABEL,Time format,Technical format for the representation of time.,NaN,False
37,COMMENT_OBS,Comments to the observation value,NaN,NaN,False
38,OBS_STATUS,Observation status,Information on the quality of a value or an unusual or missing value.,String,False
39,OBS_STATUS_LABEL,Observation status,Information on the quality of a value or an unusual or missing value.,String,False
40,OBS_CONF,Observation confidentiality,NaN,String,False
41,OBS_CONF_LABEL,Observation confidentiality,NaN,String,False

Source: https://data360.worldbank.org/en/dataset/WRI_CLIMATEWATCH

Some files are too large (FAO_AS.csv) to upload to Github. Maybe use an s3 bucket eventually.

Source: World Bank, Climate Change Knowledge Portal (2025). URL: https://climateknowledgeportal.worldbank.org/. Date Accessed:

In [27]:
# Get Climate Change Knowledge Portal API dataset about rainfall in North America

# Save url
url = 'https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_pr_timeseries_annual_1901-2024_mean_historical_cru_ts4.09_mean/region_nac?_format=json'

In [28]:
# Call the API
response = requests.get(url)
response.raise_for_status()

In [29]:
# Convert to Python dict
data = response.json()

In [30]:
# Extract the nested 'data' dict
nested_data = data['data']

In [31]:
# Build a list with data
records = []
for region_code, timeseries in nested_data.items():
    if timeseries is None:
        continue  # skip regions with no data
    for date, value in timeseries.items():
        records.append({
            "region_code": region_code,
            "date": date,
            "rainfall_mm": value
        })

In [32]:
# Now try to create a DataFrame
rainfall_df = pd.DataFrame(records)

In [33]:
# Check on the df
rainfall_df.head()

  region_code     date  rainfall_mm
0         ABW  1901-07        420.9
1         ABW  1902-07        420.9
2         ABW  1903-07        420.9
3         ABW  1904-07        420.9
4         ABW  1905-07        420.9

In [34]:
# Check rainfall_df shape
rainfall_df.shape

(622976, 3)

In [35]:
# Save rainfall_df to CSV
rainfall_df.to_csv('Resources/NA_rainfall_timeseries.csv', index=False)

In [36]:
# Let's look at unique region codes
regions = list(rainfall_df['region_code'].unique())
regions

['ABW',
 'ABW.14465',
 'AFG',
 'AFG.11',
 'AFG.110',
 'AFG.111',
 'AFG.112',
 'AFG.113',
 'AFG.114',
 'AFG.115',
 'AFG.116',
 'AFG.117',
 'AFG.118',
 'AFG.119',
 'AFG.12',
 'AFG.120',
 'AFG.121',
 'AFG.122',
 'AFG.123',
 'AFG.124',
 'AFG.125',
 'AFG.126',
 'AFG.127',
 'AFG.128',
 'AFG.129',
 'AFG.13',
 'AFG.130',
 'AFG.131',
 'AFG.132',
 'AFG.133',
 'AFG.134',
 'AFG.14',
 'AFG.15',
 'AFG.16',
 'AFG.17',
 'AFG.18',
 'AFG.19',
 'AGO',
 'AGO.8398',
 'AGO.8399',
 'AGO.8400',
 'AGO.8401',
 'AGO.8402',
 'AGO.8403',
 'AGO.8404',
 'AGO.8405',
 'AGO.8406',
 'AGO.8407',
 'AGO.8408',
 'AGO.8409',
 'AGO.8410',
 'AGO.8411',
 'AGO.8412',
 'AGO.8413',
 'AGO.8414',
 'AGO.8415',
 'AIA',
 'AIA.9416',
 'AIA.9417',
 'AIA.9418',
 'AIA.9419',
 'AIA.9420',
 'AIA.9421',
 'AIA.9422',
 'AIA.9425',
 'ALA',
 'ALA.841242',
 'ALB',
 'ALB.3305',
 'ALB.3306',
 'ALB.3307',
 'ALB.3308',
 'ALB.3309',
 'ALB.3310',
 'ALB.3311',
 'ALB.3312',
 'ALB.3313',
 'ALB.3314',
 'ALB.3315',
 'ALB.3316',
 'ALB.3317',
 'ALB.3318',
 'ALB.3319',
 'ALB.3320',
 'ALB.3321',
 'ALB.3322',
 'ALB.3323',
 'ALB.3324',
 'ALB.3325',
 'ALB.3326',
 'ALB.3327',
 'ALB.3328',
 'ALB.3329',
 'ALB.3330',
 'ALB.3331',
 'ALB.3332',
 'ALB.3333',
 'ALB.3334',
 'ALB.3335',
 'ALB.3336',
 'ALB.3337',
 'ALB.3338',
 'ALB.3339',
 'ALB.3340',
 'AND',
 'AND.7391',
 'AND.7392',
 'AND.7393',
 'AND.7394',
 'AND.7395',
 'AND.7396',
 'AND.7397',
 'ARE',
 'ARE.255149626',
 'ARE.255149627',
 'ARE.2553173',
 'ARE.2553177',
 'ARE.2553179',
 'ARE.2553180',
 'ARE.2553181',
 'ARG',
 'ARG.12429',
 'ARG.12430',
 'ARG.12431',
 'ARG.12432',
 'ARG.12433',
 'ARG.12434',
 'ARG.12435',
 'ARG.12436',
 'ARG.12437',
 'ARG.12438',
 'ARG.12439',
 'ARG.12440',
 'ARG.12441',
 'ARG.12442',
 'ARG.12443',
 'ARG.12444',
 'ARG.12445',
 'ARG.12446',
 'ARG.12447',
 'ARG.12448',
 'ARG.12449',
 'ARG.12450',
 'ARG.12451',
 'ARG.12452',
 'ARM',
 'ARM.13453',
 'ARM.13454',
 'ARM.13455',
 'ARM.13456',
 'ARM.13457',
 'ARM.13458',
 'ARM.13460',
 'ARM.13461',
 'ARM.13462',
 'ARM.13463',
 'ARM.13464',
 'ASM',
 'ASM.5389',
 'ATF',
 'ATF.881238',
 'ATF.881274',
 'ATF.881335',
 'ATF.881713',
 'ATF.882992',
 'ATG',
 'ATG.1140206',
 'ATG.1140207',
 'ATG.1140208',
 'ATG.1140209',
 'ATG.1140210',
 'ATG.1140211',
 'ATG.1140212',
 'ATG.1140213',
 'AUS',
 'AUS.17468',
 'AUS.17469',
 'AUS.17470',
 'AUS.17471',
 'AUS.17472',
 'AUS.17473',
 'AUS.17474',
 'AUS.17475',
 'AUS.17476',
 'AUS.17477',
 'AUT',
 'AUT.18478',
 'AUT.18479',
 'AUT.18480',
 'AUT.18481',
 'AUT.18482',
 'AUT.18483',
 'AUT.18484',
 'AUT.18485',
 'AUT.18486',
 'AZE',
 'AZE.19147297',
 'AZE.19147298',
 'AZE.19147299',
 'AZE.19147300',
 'AZE.19147301',
 'AZE.19147302',
 'AZE.19147303',
 'AZE.19147304',
 'AZE.19147305',
 'AZE.19147306',
 'BDI',
 'BDI.4340542',
 'BDI.4340543',
 'BDI.4340544',
 'BDI.4340545',
 'BDI.4340546',
 'BDI.4340547',
 'BDI.4340548',
 'BDI.4340549',
 'BDI.4340550',
 'BDI.4340551',
 'BDI.4340552',
 'BDI.4340553',
 'BDI.4340554',
 'BDI.4340555',
 'BDI.4340556',
 'BDI.4340557',
 'BDI.4340558',
 'BEL',
 'BEL.27600',
 'BEL.27601',
 'BEL.27602',
 'BEN',
 'BEN.29609',
 'BEN.29610',
 'BEN.29611',
 'BEN.29612',
 'BEN.29613',
 'BEN.29614',
 'BEN.29615',
 'BEN.29616',
 'BEN.29617',
 'BEN.29618',
 'BEN.29619',
 'BEN.29620',
 'BES',
 'BES.7500475104',
 'BFA',
 'BFA.4240276',
 'BFA.4240277',
 'BFA.4240278',
 'BFA.4240279',
 'BFA.4240280',
 'BFA.4240281',
 'BFA.4240282',
 'BFA.4240283',
 'BFA.4240284',
 'BFA.4240285',
 'BFA.4240286',
 'BFA.4240287',
 'BFA.4240288',
 'BGD',
 'BGD.231',
 'BGD.232',
 'BGD.233',
 'BGD.234',
 'BGD.235',
 'BGD.236',
 'BGD.237',
 'BGD.238',
 'BGR',
 'BGR.41702',
 'BGR.41703',
 'BGR.41704',
 'BGR.41705',
 'BGR.41706',
 'BGR.41707',
 'BGR.41708',
 'BGR.41709',
 'BGR.41710',
 'BGR.41711',
 'BGR.41712',
 'BGR.41713',
 'BGR.41714',
 'BGR.41715',
 'BGR.41716',
 'BGR.41717',
 'BGR.41718',
 'BGR.41719',
 'BGR.41720',
 'BGR.41721',
 'BGR.41722',
 'BGR.41723',
 'BGR.41724',
 'BGR.41725',
 'BGR.41726',
 'BGR.41727',
 'BGR.41728',
 'BGR.41729',
 'BHR',
 'BHR.21562',
 'BHR.21563',
 'BHR.21564',
 'BHR.21565',
 'BHR.21566',
 'BHR.21567',
 'BHR.21568',
 'BHR.21569',
 'BHR.21570',
 'BHR.21571',
 'BHR.21572',
 'BHR.21573',
 'BHS',
 'BHS.20561',
 'BIH',
 'BIH.34652',
 'BIH.34653',
 'BLR',
 'BLR.26593',
 'BLR.26594',
 'BLR.26595',
 'BLR.26596',
 'BLR.26597',
 'BLR.26598',
 'BLR.26599',
 'BLZ',
 'BLZ.28603',
 'BLZ.28604',
 'BLZ.28605',
 'BLZ.28606',
 'BLZ.28607',
 'BLZ.28608',
 'BMU',
 'BMU.30621',
 'BOL',
 'BOL.3340443',
 'BOL.3340444',
 'BOL.3340445',
 'BOL.3340446',
 'BOL.3340447',
 'BOL.3340448',
 'BOL.3340449',
 'BOL.3340450',
 'BOL.33648',
 'BRA',
 'BRA.37665',
 'BRA.37666',
 'BRA.37667',
 'BRA.37668',
 'BRA.37669',
 'BRA.37670',
 'BRA.37671',
 'BRA.37672',
 'BRA.37673',
 'BRA.37674',
 'BRA.37675',
 'BRA.37676',
 'BRA.37677',
 'BRA.37678',
 'BRA.37679',
 'BRA.37680',
 'BRA.37681',
 'BRA.37682',
 'BRA.37683',
 'BRA.37684',
 'BRA.37685',
 'BRA.37686',
 'BRA.37687',
 'BRA.37688',
 'BRA.37689',
 'BRA.37690',
 'BRA.37691',
 'BRA.37694',
 'BRB',
 'BRB.24581',
 'BRB.24582',
 'BRB.24583',
 'BRB.24584',
 'BRB.24585',
 'BRB.24586',
 'BRB.24587',
 'BRB.24588',
 'BRB.24589',
 'BRB.24590',
 'BRB.24591',
 'BRN',
 'BRN.40698',
 'BRN.40699',
 'BRN.40700',
 'BRN.40701',
 'BTN',
 'BTN.3141308',
 'BTN.3141309',
 'BTN.3141310',
 'BTN.3141311',
 'BTN.3141312',
 'BTN.3141313',
 'BTN.3141314',
 'BTN.31622',
 'BTN.31623',
 'BTN.31625',
 'BTN.31627',
 'BTN.31628',
 'BTN.31629',
 'BTN.31631',
 'BTN.31635',
 'BTN.31636',
 'BTN.31637',
 'BTN.31638',
 'BTN.31639',
 'BTN.31640',
 'BWA',
 'BWA.35654',
 'BWA.35655',
 'BWA.35656',
 'BWA.35657',
 'BWA.35658',
 'BWA.35659',
 'BWA.35660',
 'BWA.35661',
 'BWA.35662',
 'BWA.35663',
 'CAF',
 'CAF.4967154',
 'CAF.49853',
 'CAF.49854',
 'CAF.49855',
 'CAF.49856',
 'CAF.49857',
 'CAF.49858',
 'CAF.49859',
 'CAF.49860',
 'CAF.49861',
 'CAF.49862',
 'CAF.49863',
 'CAF.49864',
 'CAF.49865',
 'CAF.49866',
 'CAF.49867',
 'CAF.49868',
 'CAN',
 'CAN.461',
 'CAN.4610',
 'CAN.4611',
 'CAN.4612',
 'CAN.4613',
 'CAN.462',
 'CAN.463',
 'CAN.464',
 'CAN.465',
 'CAN.466',
 'CAN.467',
 'CAN.468',
 'CAN.469',
 'CCK',
 'CCK.56933',
 'CHE',
 'CHE.2372807',
 'CHE.2372808',
 'CHE.2372809',
 'CHE.2372810',
 'CHE.2372811',
 'CHE.2372812',
 'CHE.2372813',
 'CHE.2372814',
 'CHE.2372815',
 'CHE.2372816',
 'CHE.2372817',
 'CHE.2372818',
 'CHE.2372819',
 'CHE.2372820',
 'CHE.2372821',
 'CHE.2372822',
 'CHE.2372823',
 'CHE.2372824',
 'CHE.2372825',
 'CHE.2372826',
 'CHE.2372827',
 'CHE.2372828',
 'CHE.2372829',
 'CHE.2372830',
 'CHE.2372831',
 'CHE.2372832',
 'CHL',
 'CHL.51149630',
 'CHL.51883',
 'CHL.51884',
 'CHL.51885',
 'CHL.51886',
 'CHL.51887',
 'CHL.51888',
 'CHL.51889',
 'CHL.51891',
 'CHL.51892',
 'CHL.51893',
 'CHL.5191501',
 'CHL.5191502',
 'CHL.5191503',
 'CHL.5191504',
 'CHN',
 'CHN.147295898',
 'CHN.147295899',
 'CHN.147295900',
 'CHN.147295901',
 'CHN.147295902',
 'CHN.147295903',
 'CHN.147295904',
 'CHN.147295905',
 'CHN.147295906',
 'CHN.147295907',
 'CHN.147295908',
 'CHN.147295909',
 'CHN.147295911',
 'CHN.147295912',
 'CHN.147295913',
 'CHN.147295914',
 'CHN.147295915',
 'CHN.147295916',
 'CHN.147295917',
 'CHN.147295918',
 'CHN.147295919',
 'CHN.147295920',
 'CHN.147295921',
 'CHN.147295922',
 'CHN.147295923',
 'CHN.147295924',
 'CHN.147295926',
 'CHN.147295927',
 'CHN.147295928',
 'CHN.147295929',
 'CHN.147295930',
 'CIV',
 'CIV.661',
 'CIV.6610',
 'CIV.6611',
 'CIV.6612',
 'CIV.6613',
 'CIV.6614',
 'CIV.662',
 'CIV.663',
 'CIV.664',
 'CIV.665',
 'CIV.666',
 'CIV.667',
 'CIV.668',
 'CIV.669',
 'CMR',
 'CMR.45815',
 'CMR.45816',
 'CMR.45817',
 'CMR.45818',
 'CMR.45819',
 'CMR.45820',
 'CMR.45821',
 'CMR.45822',
 'CMR.45823',
 'CMR.45824',
 'COD',
 'COD.681066',
 'COD.681067',
 'COD.681068',
 'COD.681069',
 'COD.681070',
 'COD.681071',
 'COD.681072',
 'COD.681073',
 'COD.681074',
 'COD.681075',
 'COD.681076',
 'COD.681077',
 'COD.681078',
 'COD.681079',
 'COD.681080',
 'COD.681081',
 'COD.681082',
 'COD.681083',
 'COD.681084',
 'COD.681085',
 'COD.681086',
 'COD.681087',
 'COD.681088',
 'COD.681089',
 'COD.681090',
 'COD.681091',
 'COG',
 'COG.59190431',
 'COG.59190432',
 'COG.59190433',
 'COG.59190434',
 'COG.59970',
 'COG.59971',
 'COG.59972',
 'COG.59974',
 'COG.59975',
 'COG.59976',
 'COG.59977',
 'COG.59979',
 'COK',
 'COK.60980',
 'COL',
 'COL.57934',
 'COL.57935',
 'COL.57936',
 'COL.57937',
 'COL.57938',
 'COL.57939',
 'COL.57941',
 'COL.57942',
 'COL.57943',
 'COL.57944',
 'COL.57945',
 'COL.57946',
 'COL.57947',
 'COL.57948',
 'COL.579481',
 'COL.57949',
 'COL.57950',
 'COL.57951',
 'COL.57952',
 'COL.57953',
 'COL.57954',
 'COL.57955',
 'COL.57956',
 'COL.57957',
 'COL.57958',
 'COL.57959',
 'COL.57960',
 'COL.57961',
 'COL.57962',
 'COL.57963',
 'COL.57964',
 'COL.57965',
 'COL.57966',
 'COM',
 'COM.58967',
 'COM.58968',
 'COM.58969',
 'CPV',
 'CPV.47838',
 'CPV.47839',
 'CPV.47840',
 'CPV.47841',
 'CPV.47842',
 'CPV.47843',
 'CPV.47844',
 'CPV.47845',
 'CPV.47846',
 'CPV.47847',
 'CPV.47848',
 'CPV.47849',
 'CPV.47850',
 'CPV.47851',
 'CRI',
 'CRI.61981',
 'CRI.61982',
 'CRI.61983',
 'CRI.61984',
 'CRI.61985',
 'CRI.61986',
 'CRI.61987',
 'CUB',
 'CUB.631009',
 'CUB.631010',
 'CUB.631011',
 'CUB.631012',
 'CUB.631013',
 'CUB.631014',
 'CUB.631015',
 'CUB.631016',
 'CUB.631017',
 'CUB.631018',
 'CUB.631019',
 'CUB.631020',
 'CUB.631021',
 'CUB.631022',
 'CUB.631023',
 'CUW',
 'CUW.7500275102',
 'CXR',
 'CXR.54931',
 'CYM',
 'CYM.4868742',
 'CYP',
 'CYP.6475401',
 'CYP.6475403',
 'CYP.6475404',
 'CYP.6475405',
 'CYP.6475406',
 'CYP.6475407',
 'CZE',
 'CZE.651030',
 'CZE.651031',
 'CZE.651032',
 'CZE.651033',
 'CZE.651034',
 'CZE.651035',
 'CZE.651036',
 'CZE.651037',
 'DEU',
 'DEU.931308',
 'DEU.931309',
 'DEU.931310',
 'DEU.931311',
 'DEU.931312',
 'DEU.931313',
 'DEU.931314',
 'DEU.931315',
 'DEU.931316',
 'DEU.931317',
 'DEU.931318',
 'DEU.931319',
 'DEU.931320',
 'DEU.931321',
 'DEU.931322',
 'DEU.931323',
 'DIS.990011',
 'DIS.990022',
 'DIS.990044',
 'DIS.990055',
 'DIS.990066',
 'DIS.990099',
 'DIS.9901212',
 'DIS.9901313',
 'DIS.9901414',
 'DIS.9901515',
 'DIS.9901616',
 'DIS.9901717',
 'DIS.9901818',
 'DIS.9901919',
 'DIS.9902020',
 'DIS.9902121',
 'DIS.9902222',
 'DIS.9902323',
 'DIS.9902424',
 'DIS.9902626',
 'DIS.9902727',
 'DIS.9902828',
 'DIS.9902929',
 'DIS.9903030',
 'DIS.9903131',
 'DISPUTED',
 'DIV002418',
 'DIV003449',
 'DIV083903',
 'DIV086580',
 'DJI',
 'DJI.701',
 'DJI.702',
 'DJI.703',
 'DJI.704',
 'DJI.705',
 'DMA',
 'DMA.711098',
 'DMA.711099',
 'DMA.711100',
 'DMA.711101',
 'DMA.711102',
 'DMA.711103',
 'DMA.711104',
 'DMA.711105',
 'DMA.711106',
 'DMA.711107',
 'DNK',
 'DNK.691',
 'DNK.692',
 'DNK.693',
 'DNK.694',
 'DNK.695',
 'DOM',
 'DOM.721108',
 'DOM.721109',
 'DOM.721110',
 'DOM.721111',
 'DOM.721112',
 'DOM.721113',
 'DOM.721114',
 'DOM.721115',
 'DOM.721116',
 'DOM.721117',
 'DOM.721118',
 'DOM.721119',
 'DOM.721120',
 'DOM.721121',
 'DOM.721122',
 'DOM.721123',
 'DOM.721124',
 'DOM.721125',
 'DOM.721126',
 'DOM.721127',
 'DOM.721128',
 'DOM.721129',
 'DOM.721130',
 'DOM.721131',
 'DOM.721132',
 'DOM.721133',
 'DOM.721134',
 'DOM.7236854',
 'DOM.7236855',
 'DOM.7236856',
 'DOM.7236857',
 'DOM.7236858',
 'DZA',
 'DZA.4341',
 'DZA.4342',
 'DZA.4343',
 'DZA.4344',
 'DZA.4345',
 'DZA.4346',
 'DZA.4347',
 'DZA.4348',
 'DZA.4349',
 'DZA.4350',
 'DZA.4351',
 'DZA.4352',
 'DZA.4353',
 'DZA.4354',
 'DZA.4355',
 'DZA.4356',
 'DZA.4357',
 'DZA.4358',
 'DZA.4359',
 'DZA.4360',
 'DZA.4361',
 'DZA.4362',
 'DZA.4363',
 'DZA.4364',
 'DZA.4365',
 'DZA.4366',
 'DZA.4367',
 'DZA.4368',
 'DZA.4369',
 'DZA.4370',
 'DZA.4371',
 'DZA.4372',
 'DZA.4373',
 'DZA.4374',
 'DZA.4375',
 'DZA.4376',
 'DZA.4377',
 'DZA.4378',
 'DZA.4379',
 'DZA.4380',
 'DZA.4381',
 'DZA.4382',
 'DZA.4383',
 'DZA.4384',
 'DZA.4385',
 'DZA.4386',
 'DZA.4387',
 'DZA.4388',
 'EAP000001',
 'EAP000302',
 'EAP000369',
 'EAP000370',
 'EAP000422',
 'EAP000423',
 'EAP000480',
 'EAP000481',
 'EAP000505',
 'EAP000514',
 'EAP000515',
 'EAP000572',
 'EAP000583',
 'EAP000652',
 'EAP000653',
 'EAP000657',
 'EAP000658',
 'EAP000669',
 'EAP000690',
 'EAP000694',
 'EAP000708',
 'EAP000709',
 'EAP000738',
 'EAP000740',
 'EAP000741',
 'EAP000742',
 'EAP000766',
 'EAP000767',
 'EAP000769',
 'EAP000785',
 'EAP000786',
 'EAP000988',
 'EAP000989',
 'EAP001169',
 'EAP001180',
 'EAP001228',
 'EAP001229',
 'EAP001277',
 'EAP001278',
 'EAP001299',
 'EAP001300',
 'EAP001402',
 'EAP001500',
 'EAP001501',
 'EAP001509',
 'EAP001566',
 'EAP001582',
 'EAP001583',
 'EAP001702',
 'EAP001703',
 'EAP001704',
 'EAP001782',
 'EAP001783',
 'EAP001835',
 'EAP002118',
 'EAP002119',
 'EAP002220',
 'EAP002250',
 'EAP002279',
 'EAP002305',
 'EAP002306',
 'EAP002307',
 'EAP002321',
 'EAP002322',
 'EAP002323',
 'EAP002381',
 'EAP002382',
 'EAP002419',
 'EAP002431',
 'EAP003124',
 'EAP003727',
 'EAP003894',
 'EAP004004',
 'EAP004036',
 'EAP004123',
 'EAP004124',
 'EAP004187',
 'EAP004188',
 'EAP004578',
 'EAP004637',
 'EAP004691',
 'EAP004692',
 'EAP004750',
 'EAP004772',
 'EAP004773',
 'EAP005021',
 'EAP005026',
 'EAP005027',
 'EAP005028',
 'EAP005029',
 'EAP005031',
 'EAP005032',
 'EAP005034',
 'EAP005037',
 'EAP005038',
 'EAP005039',
 'EAP005041',
 'EAP005043',
 'EAP005044',
 'EAP005045',
 'EAP005047',
 'EAP005048',
 'EAP005052',
 'EAP005055',
 'EAP005058',
 'EAP005059',
 'EAP005061',
 'EAP005070',
 'EAP005074',
 'EAP005078',
 'EAP005079',
 'EAP005081',
 'EAP005083',
 'EAP005085',
 'EAP005090',
 'EAP005091',
 'EAP005094',
 'EAP005095',
 'EAP005098',
 'EAP005110',
 'EAP005121',
 'EAP005127',
 'EAP005153',
 'EAP005314',
 'EAP005488',
 'EAP005542',
 'EAP005587',
 'EAP005595',
 'EAP008155',
 'EAP009532',
 'EAP013625',
 'EAP018680',
 'EAP041619',
 'EAP041643',
 'EAP043803',
 'EAP043813',
 'EAP044966',
 'EAP044999',
 'EAP046269',
 'EAP046293',
 'EAP054826',
 'EAP054837',
 'EAP057864',
 'EAP057883',
 'EAP060357',
 'EAP060374',
 'EAP062725',
 'EAP062762',
 'EAP067975',
 'EAP067976',
 'EAP069419',
 'EAP069435',
 'EAP074830',
 'EAP074831',
 ...]

In [37]:
# Try to get only North American data
north_america_codes = ['CAN', 'USA']  # add more if needed
rainfall_df_na = rainfall_df[rainfall_df['region_code'].str.startswith(tuple(north_america_codes))]

In [38]:
rainfall_df_na.head()

      region_code     date  rainfall_mm
54064         CAN  1901-07       538.38
54065         CAN  1902-07       549.26
54066         CAN  1903-07       540.08
54067         CAN  1904-07       531.71
54068         CAN  1905-07       531.56

In [39]:
# Look at rainfall_na_df
rainfall_df_na.shape

(8184, 3)

In [40]:
# Check for na
rainfall_df_na.isna().sum()

region_code    0
date           0
rainfall_mm    0
dtype: int64

In [41]:
# Check unique entries in 'region_code'
rainfall_df_na['region_code'].unique()

array(['CAN', 'CAN.461', 'CAN.4610', 'CAN.4611', 'CAN.4612', 'CAN.4613',
       'CAN.462', 'CAN.463', 'CAN.464', 'CAN.465', 'CAN.466', 'CAN.467',
       'CAN.468', 'CAN.469', 'USA', 'USA.2593214', 'USA.2593215',
       'USA.2593216', 'USA.2593217', 'USA.2593218', 'USA.2593219',
       'USA.2593220', 'USA.2593221', 'USA.2593222', 'USA.2593223',
       'USA.2593224', 'USA.2593225', 'USA.2593226', 'USA.2593227',
       'USA.2593228', 'USA.2593229', 'USA.2593230', 'USA.2593231',
       'USA.2593232', 'USA.2593233', 'USA.2593234', 'USA.2593235',
       'USA.2593236', 'USA.2593237', 'USA.2593238', 'USA.2593239',
       'USA.2593240', 'USA.2593241', 'USA.2593242', 'USA.2593243',
       'USA.2593244', 'USA.2593245', 'USA.2593246', 'USA.2593247',
       'USA.2593248', 'USA.2593249', 'USA.2593250', 'USA.2593251',
       'USA.2593252', 'USA.2593253', 'USA.2593254', 'USA.2593255',
       'USA.2593256', 'USA.2593257', 'USA.2593258', 'USA.2593259',
       'USA.2593260', 'USA.2593261', 'USA.2593262', 'USA.2593263',
       'USA.2593264'], dtype=object)

Let's use the provided raster file to understand what these regions are.

It was uploaded to an s3 bucket, first let's retrieve it from there.

In [42]:
# Get s3 url
url = "https://portfolio-5867-9443-9985.s3.us-east-2.amazonaws.com/timeseries-pr-annual-mean_cru-x0.5_cru-ts4.09-historical_timeseries_mean_1901-2024.nc"

In [43]:
# Save NetCDF file to disk using streaming
with requests.get(url, stream=True) as response:
    if response.status_code == 200:
        with open("Resources/raster_file.nc", "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:  # filter out keep-alive chunks
                    f.write(chunk)
        print("Download complete.")
    else:
        print(f"Failed to retrieve the file. Status code: {response.status_code}")

Download complete.

In [44]:
# Open NetCDF file
ds = xr.open_dataset("Resources/raster_file.nc")

In [45]:
# Preview variables
ds

<xarray.Dataset>
Dimensions:                    (time: 124, lat: 360, lon: 720, bnds: 2)
Coordinates:
  * time                       (time) datetime64[ns] 1901-07-01 ... 2024-07-01
  * lat                        (lat) float32 -89.75 -89.25 ... 89.25 89.75
  * lon                        (lon) float32 -179.8 -179.2 ... 179.2 179.8
  * bnds                       (bnds) int32 0 1
Data variables:
    timeseries-pr-annual-mean  (time, lat, lon) float32 ...
    lon_bnds                   (lon, bnds) float64 ...
    lat_bnds                   (lat, bnds) float64 ...
Attributes: (12/23)
    wb_truncation_label:   2
    wb_grid_label:         x0.5
    wb_period_label:       1901-2024
    wb_percentile_label:   mean
    wb_type_label:         timeseries
    wb_model_label:        cru
    ...                    ...
    source:                Run ID = 2503051245. Data generated from:pre.25030...
    institution:           Data held at British Atmospheric Data Centre, RAL,...
    title:                 CRU TS4.09 Precipitation
    Conventions:           CF-1.4
    wb_OBS:                 \nwb_creation_date = Sat Apr 26 02:55:23 PM MDT 2...
    wb:                     \nwb_access_citation = Please acknowledge data so...

In [46]:

# Convert to CSV (assumes 2D array or manageable data)
raster_df = ds.to_dataframe().reset_index()

# View df
raster_df.head()

,time,lat,lon,bnds,timeseries-pr-annual-mean,lon_bnds,lat_bnds
0,1901-07-01,-89.75,-179.75,0,NaN,-180.0,-90.0
1,1901-07-01,-89.75,-179.75,1,NaN,-179.5,-89.5
2,1901-07-01,-89.75,-179.25,0,NaN,-179.5,-90.0
3,1901-07-01,-89.75,-179.25,1,NaN,-179.0,-89.5
4,1901-07-01,-89.75,-178.75,0,NaN,-179.0,-90.0

In [48]:
# Look at the same column
raster_df['timeseries-pr-annual-mean'].isna().sum()

47561440

In [49]:
# Still looking
raster_df['timeseries-pr-annual-mean'].notna().sum()

16720160

Most of the entries are NaN, likely the ones outside Canada and the USA.

In [50]:
# Filter for USA
usa_mask = (
    (raster_df['lat'] >= 24.5) & (raster_df['lat'] <= 49.5) &
    (raster_df['lon'] >= -125) & (raster_df['lon'] <= -66.9)
)

# Filter for Canada
canada_mask = (
    (raster_df['lat'] >= 41.7) & (raster_df['lat'] <= 83.1) &
    (raster_df['lon'] >= -141) & (raster_df['lon'] <= -52.6)
)

# Combine both masks
north_america_mask = usa_mask | canada_mask

# Apply filter
raster_df_filtered = raster_df[north_america_mask].copy()

In [51]:
# Look at new raster_df_filtered
raster_df_filtered.head()

,time,lat,lon,bnds,timeseries-pr-annual-mean,lon_bnds,lat_bnds
329980,1901-07-01,24.75,-124.75,0,NaN,-125.0,24.5
329981,1901-07-01,24.75,-124.75,1,NaN,-124.5,25.0
329982,1901-07-01,24.75,-124.25,0,NaN,-124.5,24.5
329983,1901-07-01,24.75,-124.25,1,NaN,-124.0,25.0
329984,1901-07-01,24.75,-123.75,0,NaN,-124.0,24.5

In [52]:
# Look for NaN
raster_df_filtered.isna().sum()

time                               0
lat                                0
lon                                0
bnds                               0
timeseries-pr-annual-mean    1581744
lon_bnds                           0
lat_bnds                           0
dtype: int64

In [53]:
# Look for Not Na
raster_df_filtered.notna().sum()

time                         4621480
lat                          4621480
lon                          4621480
bnds                         4621480
timeseries-pr-annual-mean    3039736
lon_bnds                     4621480
lat_bnds                     4621480
dtype: int64

timeseries column now has not na: 3039736
previously had                  : 16720160

so we've lost a substanial amount of entries, and still have 1581744 Nan

In [54]:
# Shape of raster_df_filtered
raster_df_filtered.shape

(4621480, 7)

After all that the raster file might not provide what I was hoping. Unfortunate.

Let's try to look at some Canada crop yield data.

In [56]:
# Load Our World in Data CO2 data ('owid-co2-data.csv')
canada_crops_df = pd.read_csv('Resources/3210035901_databaseLoadingData.csv')
canada_crops_df.head()

,REF_DATE,GEO,DGUID,Harvest disposition,Type of crop,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1908,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,580600.0,NaN,NaN,NaN,0
1,1909,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,489600.0,NaN,NaN,NaN,0
2,1910,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,363600.0,NaN,NaN,NaN,0
3,1911,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,487400.0,NaN,NaN,NaN,0
4,1912,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,430100.0,NaN,NaN,NaN,0

In [57]:
canada_crops_df.tail()

,REF_DATE,GEO,DGUID,Harvest disposition,Type of crop,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
703,2021,Canada,2021A000011124,Production (metric tonnes),"Wheat, winter remaining",Metric tonnes,214,units,0,v114995756,1.19.3,3227759.0,NaN,NaN,NaN,0
704,2022,Canada,2021A000011124,Production (metric tonnes),"Wheat, winter remaining",Metric tonnes,214,units,0,v114995756,1.19.3,2852803.0,NaN,r,NaN,0
705,2023,Canada,2021A000011124,Production (metric tonnes),"Wheat, winter remaining",Metric tonnes,214,units,0,v114995756,1.19.3,3341757.0,NaN,r,NaN,0
706,2024,Canada,2021A000011124,Production (metric tonnes),"Wheat, winter remaining",Metric tonnes,214,units,0,v114995756,1.19.3,3043363.0,NaN,r,NaN,0
707,2025,Canada,2021A000011124,Production (metric tonnes),"Wheat, winter remaining",Metric tonnes,214,units,0,v114995756,1.19.3,3477773.0,NaN,NaN,NaN,0

Data retrieved from Stats Can : https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=3210035901

Luckily this loaded pretty easily! Now let's try to get one for the USA.

In [58]:
# import API KEY
from Resources import USDA_API_KEY

In [62]:
# Quick USDA API attempt
url = (
    "https://quickstats.nass.usda.gov/api/api_GET/"
    "?key=" + USDA_API_KEY +
    "&source_desc=SURVEY"
    "&sector_desc=CROPS"
    "&commodity_desc=CORN"
    "&statisticcat_desc=YIELD"
    "&agg_level_desc=STATE"
    "&year__GE=2000"
    "&format=CSV"
)

TypeError: can only concatenate str (not "module") to str