In [26]:
import pandas as pd

In [27]:
# Load Our World in Data CO2 data ('owid-co2-data.csv')
owid_co2_df = pd.read_csv('Resources/owid-co2-data.csv')
owid_co2_df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# Look at year range for entire notebook
year_min = owid_co2_df['year'].min()
year_max = owid_co2_df['year'].max()

# Print statement of min/max years
print(f"The earliest year recorded in this OWID CO2 dataset: {year_min}. ")
print(f"The latest year recorded in this OWID CO2 dataset:   {year_max}. ")

The earliest year recorded in this OWID CO2 dataset: 1750.
The latest year recorded in this OWID CO2 dataset:   2023.

In [29]:
# Look at unique countries in the dataset
country_list = owid_co2_df['country'].unique()

country_sum = owid_co2_df['country'].nunique()

print(f"There are {country_sum} countries in this dataset.")
print(f"The following countries are represented in the dataset: {country_list}")

There are 255 countries in this dataset.
The following countries are represented in the dataset: ['Afghanistan' 'Africa' 'Africa (GCP)' 'Albania' 'Algeria' 'Andorra'
 'Angola' 'Anguilla' 'Antarctica' 'Antigua and Barbuda' 'Argentina'
 'Armenia' 'Aruba' 'Asia' 'Asia (GCP)' 'Asia (excl. China and India)'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bonaire Sint Eustatius and Saba' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'British Virgin Islands' 'Brunei' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde'
 'Central African Republic' 'Central America (GCP)' 'Chad' 'Chile' 'China'
 'Christmas Island' 'Colombia' 'Comoros' 'Congo' 'Cook Islands'
 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus'
 'Czechia' 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'East Timor' 'Ecuador' 'Egypt' 'El Salvador'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'Europe (GCP)' 'Europe (excl. EU-27)' 'Europe (excl. EU-28)'
 'European Union (27)' 'European Union (28)' 'Faroe Islands' 'Fiji'
 'Finland' 'France' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Greece' 'Greenland' 'Grenada' 'Guatemala' 'Guinea'
 'Guinea-Bissau' 'Guyana' 'Haiti' 'High-income countries' 'Honduras'
 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia'
 'International aviation' 'International shipping'
 'International transport' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kosovo'
 'Kuwait' 'Kuwaiti Oil Fires' 'Kuwaiti Oil Fires (GCP)' 'Kyrgyzstan'
 'Laos' 'Latvia' 'Least developed countries (Jones et al.)' 'Lebanon'
 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania'
 'Low-income countries' 'Lower-middle-income countries' 'Luxembourg'
 'Macao' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia (country)' 'Middle East (GCP)' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua'
 'Niger' 'Nigeria' 'Niue' 'Non-OECD (GCP)' 'North America'
 'North America (GCP)' 'North America (excl. USA)' 'North Korea'
 'North Macedonia' 'Norway' 'OECD (GCP)' 'OECD (Jones et al.)' 'Oceania'
 'Oceania (GCP)' 'Oman' 'Pakistan' 'Palau' 'Palestine' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Ryukyu Islands'
 'Ryukyu Islands (GCP)' 'Saint Helena' 'Saint Kitts and Nevis'
 'Saint Lucia' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Sint Maarten (Dutch part)' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South America'
 'South America (GCP)' 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka'
 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan'
 'Tanzania' 'Thailand' 'Togo' 'Tonga' 'Trinidad and Tobago' 'Tunisia'
 'Turkey' 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'United States'
 'Upper-middle-income countries' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Vatican' 'Venezuela' 'Vietnam' 'Wallis and Futuna' 'World' 'Yemen'
 'Zambia' 'Zimbabwe']

For the purpose of this project we only want to see results from Canada and the United States, and only frmo 1908 to present day.

In [30]:
# Filter dataset for only Canada and the United States
filtered_df = owid_co2_df[owid_co2_df['country'].isin(['Canada', 'United States'])]

remaining_countries = filtered_df['country'].unique()

print(f"The remainging countries after filtering are: {remaining_countries}")

The remainging countries after filtering are: ['Canada' 'United States']

In [31]:
# Look at min/max range of year in filtered_df
filtered_year_min = filtered_df['year'].min()
filtered_year_max = filtered_df['year'].max()

print(f"The earliest year in the filtered Canada and USA dataset: {filtered_year_min}")
print(f"The latest year in the filtered Canada and USA dataset:   {filtered_year_max}")

The earliest year in the filtered Canada and USA dataset: 1785
The latest year in the filtered Canada and USA dataset:   2023

In [32]:
# Filter out dates before 1908
post_1908_df = filtered_df[filtered_df['year'] >= 1908]
post_1908_df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
8720,Canada,1908,CAN,6663003.0,3.879322e+10,NaN,NaN,47.408,0.418,0.889,...,NaN,2.400,0.001,0.003,0.004,0.0,272.132,65.440,NaN,NaN
8721,Canada,1909,CAN,6835990.0,4.291604e+10,NaN,NaN,45.386,-2.023,-4.266,...,NaN,2.418,0.001,0.003,0.004,0.0,313.675,63.555,NaN,NaN
8722,Canada,1910,CAN,7002961.0,4.658543e+10,NaN,NaN,51.622,6.236,13.740,...,NaN,2.435,0.001,0.003,0.004,0.0,311.472,70.344,NaN,NaN
8723,Canada,1911,CAN,7163537.0,4.975815e+10,NaN,NaN,60.269,8.647,16.751,...,NaN,2.453,0.001,0.004,0.004,0.0,321.194,79.696,NaN,NaN
8724,Canada,1912,CAN,7317326.0,5.303915e+10,NaN,NaN,67.271,7.002,11.618,...,NaN,2.479,0.001,0.004,0.005,0.0,356.461,87.262,NaN,NaN

Some good work here eliminating all but Canada and the USA, and also extra years before 1908. Dates before 1908 were eliminated to line up with crop yield datasets to come later (Stats Canada and USDA).

There are still a ton of columns here, some can definitely be dropped.

In [33]:
# Look at the columns
post_1908_df.columns

Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share'],
      dtype='object')

In [34]:
post_1908_reduced_df = post_1908_df[['country', 'year', 'iso_code', 'population', 'gdp',
                                               'co2', 'co2_growth_prct', 'co2_per_capita', 
                                               'co2_per_gdp', 'total_ghg']]

post_1908_reduced_df.head()

,country,year,iso_code,population,gdp,co2,co2_growth_prct,co2_per_capita,co2_per_gdp,total_ghg
8720,Canada,1908,CAN,6663003.0,3.879322e+10,47.408,0.889,7.115,1.222,272.132
8721,Canada,1909,CAN,6835990.0,4.291604e+10,45.386,-4.266,6.639,1.058,313.675
8722,Canada,1910,CAN,7002961.0,4.658543e+10,51.622,13.740,7.371,1.108,311.472
8723,Canada,1911,CAN,7163537.0,4.975815e+10,60.269,16.751,8.413,1.211,321.194
8724,Canada,1912,CAN,7317326.0,5.303915e+10,67.271,11.618,9.193,1.268,356.461

In [35]:
post_1908_reduced_df.tail()

,country,year,iso_code,population,gdp,co2,co2_growth_prct,co2_per_capita,co2_per_gdp,total_ghg
47795,United States,2019,USA,337790068.0,1.854055e+13,5262.145,-2.151,15.578,0.284,6216.229
47796,United States,2020,USA,339436157.0,1.802736e+13,4714.628,-10.405,13.890,0.262,5651.509
47797,United States,2021,USA,340161441.0,1.909938e+13,5032.213,6.736,14.794,0.263,6009.153
47798,United States,2022,USA,341534041.0,1.949317e+13,5078.871,0.927,14.871,0.261,6067.148
47799,United States,2023,USA,343477332.0,NaN,4911.391,-3.298,14.299,NaN,5894.857

In [36]:
post_1908_reduced_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 232 entries, 8720 to 47799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          232 non-null    object
 1   year             232 non-null    int64
 2   iso_code         232 non-null    object
 3   population       232 non-null    float64
 4   gdp              230 non-null    float64
 5   co2              232 non-null    float64
 6   co2_growth_prct  232 non-null    float64
 7   co2_per_capita   232 non-null    float64
 8   co2_per_gdp      230 non-null    float64
 9   total_ghg        232 non-null    float64
dtypes: float64(7), int64(1), object(2)
memory usage: 19.9+ KB

In [38]:
# Look for Nan entries
post_1908_reduced_df.isnull().sum()

country            0
year               0
iso_code           0
population         0
gdp                2
co2                0
co2_growth_prct    0
co2_per_capita     0
co2_per_gdp        2
total_ghg          0
dtype: int64

In [40]:
# Look for NaN rows
nan_rows = post_1908_reduced_df[post_1908_reduced_df.isnull().any(axis=1)]
nan_rows

,country,year,iso_code,population,gdp,co2,co2_growth_prct,co2_per_capita,co2_per_gdp,total_ghg
8835,Canada,2023,CAN,39299099.0,NaN,549.299,-0.238,13.977,NaN,800.006
47799,United States,2023,USA,343477332.0,NaN,4911.391,-3.298,14.299,NaN,5894.857

Encouragingly there are only 4 total NaN entries in this dataset. They both refer to GDP in 2023, presumably the dataset was made before these numbers were released, or at least they were unavailable at that time. GPD is not vital to this project, but for now we will keep this row, the rest of the data is important.