In [1]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\nbart.desktop-3of7m8n\anaconda3\envs\dev\lib\site-packages (2.9.10)
Requirement already satisfied: sqlalchemy in c:\users\nbart.desktop-3of7m8n\anaconda3\envs\dev\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nbart.desktop-3of7m8n\anaconda3\envs\dev\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nbart.desktop-3of7m8n\anaconda3\envs\dev\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [9]:
# import dependencies
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text
import Resources.postgres_key as pk
import importlib

In [3]:
# Setup up credentials
user = pk.postgres_user
password = pk.postgres_pass

In [6]:
# Create engine
engine = create_engine(
    f"postgresql+psycopg2://{user}:{password}@climate-db.croamw4iqxpi.us-east-2.rds.amazonaws.com:5432/climate_db"
)

In [ ]:
# Test the connecttion
try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT 1"))
        print(result.fetchone())  # Should print (1,)
except Exception as e:
    print("Connection failed:", e)

(1,)

The connection works, now let's load all of the CSV files from the Output directory and send them to the PostgreSQL database.

In [19]:
# Load all of the Output CSV files as pandas dfs
co2_df = pd.read_csv("Output/co2_df.csv", index_col=0)
diet_percentage_df = pd.read_csv("Output/diet_percentage_df.csv", index_col=0)
diet_persons_df = pd.read_csv("Output/diet_persons_df.csv", index_col=0)
NA_crops_df = pd.read_csv("Output/NA_crops_df.csv", index_col=0)
rainfall_df = pd.read_csv("Output/rainfall_df.csv", index_col=0)

In [20]:
# View co2_df
co2_df.head()

,country,iso_code,year,population,gdp,co2,co2_growth_prct,co2_per_capita,co2_per_gdp,total_ghg
0,Canada,CAN,2023,39299099,NaN,549.299,-0.238,13.977,NaN,800.006
1,United States,USA,2023,343477332,NaN,4911.391,-3.298,14.299,NaN,5894.857
2,Canada,CAN,2022,38821260,1.761296e+12,550.612,1.906,14.183,0.313,810.218
3,United States,USA,2022,341534041,1.949317e+13,5078.871,0.927,14.871,0.261,6067.148
4,Canada,CAN,2021,38454058,1.703443e+12,540.312,2.607,14.051,0.317,773.065

In [21]:
# View diet_percentage_df
diet_percentage_df.head()

         country iso_code  year unit_of_measure  percentage
0         Canada      CAN  2023      percentage         3.0
1  United States      USA  2023      percentage         4.7
2         Canada      CAN  2022      percentage         2.7
3  United States      USA  2022      percentage         4.7
4         Canada      CAN  2021      percentage         3.0

In [22]:
# View diet_persons_df
diet_persons_df.head()

         country iso_code  year unit_of_measure  total_million
0         Canada      CAN  2023         persons            1.2
1  United States      USA  2023         persons           16.3
2         Canada      CAN  2022         persons            1.1
3  United States      USA  2022         persons           16.2
4         Canada      CAN  2021         persons            1.2

In [23]:
# View NA_crops_df
NA_crops_df.head()

         country iso_code  year   crop  production_mt
0         Canada      CAN  2023   corn   1.542091e+07
1         Canada      CAN  2023  wheat   3.341360e+07
2  United States      USA  2023   corn   3.896676e+08
3  United States      USA  2023  wheat   4.909518e+07
4         Canada      CAN  2022   corn   1.453888e+07

In [24]:
# View rainfall_df
rainfall_df.head()

         country iso_code  year  total_precip_mm
2         Canada      CAN  2023       698.600714
3  United States      USA  2023       954.099808
4         Canada      CAN  2022       722.494286
5  United States      USA  2022       924.875962
6         Canada      CAN  2021       715.488571

They all look OK now. Had to use "index_col=0" when reading CSVs. Next time will writing CSVs use "index=False" to avoid creating a new index column.

Now let's try to load them all to the database.

In [25]:
# Load to SQL database
co2_df.to_sql('co2', engine, if_exists="replace", index=False)
diet_percentage_df.to_sql('diet_percentage', engine, if_exists="replace", index=False)
diet_persons_df.to_sql('diet_persons', engine, if_exists="replace", index=False)
NA_crops_df.to_sql('NA_crops', engine, if_exists="replace", index=False)
rainfall_df.to_sql("rainfall", engine, if_exists="replace", index=False)

232

Let's quickly check to see if the tables are there.

In [26]:
# Check co2 table
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM co2"))
    print(result.scalar())  # should print 232

232

In [27]:
# Check rainfall table
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM rainfall LIMIT 5"))
    for row in result:
        print(row)

('Canada', 'CAN', 2023, 698.6007142857143)
('United States', 'USA', 2023, 954.0998076923078)
('Canada', 'CAN', 2022, 722.4942857142858)
('United States', 'USA', 2022, 924.8759615384616)
('Canada', 'CAN', 2021, 715.4885714285714)

It seems like the tables are there!